FROM golang:1.22.1 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF


COPY . /service

WORKDIR /service/app/services/sales-api
RUN go build -ldflags "-X main.build=${BUILD_REF}"


FROM alpine:3.19.1
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_sales-api /service/app/services/sales-api/sales-api /service/sales-api
WORKDIR /service
CMD ["./sales-api"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="Marcos Vieira Jr <marcosvieirajr@gmail.com>" \
      org.opencontainers.image.source="https://github.com/marcosvieirajr/service/app/sales-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="MVj"
