# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- ../../base/sales-pod
patches:
- path: base-sales-patch.yaml
images:
- name: sales-api-image
  newName: sales-api-amd64
  newTag: "1.0"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
